apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wolke7-nocode-portainer
  namespace: argocd
spec:
  destination:
    name: wolke7-nocode
    namespace: portainer
  project: default
  source:
    path: portainer
    repoURL: https://github.com/ripro-patrick/wolke7-helm-subcharts.git
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true