apiVersion: v1
kind: Namespace
metadata:
  name: wolke7-nocode
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wolke7-nocode-cluster
  namespace: argocd
spec:
  destination:
    name: wolke7-infra
    namespace: argocd
  project: default
  source:
    path: infra
    repoURL: https://github.com/ripro-patrick/wolke7-nocode.git
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: deploy-argocd-cluster-config
  namespace: argocd
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/argoproj/argocd:v2.0.4
        name: deploy-argocd-cluster-config
        command: ["/bin/sh"]
        args: ["-c", "argocd login http://argocd-server --insecure --username=admin --password=$(cat /tmp/argocd-initial-admin-secret/password) --grpc-web  ; argocd cluster add --grpc-web wolke7-nocode --kubeconfig /tmp/cluster-details-wolke7-nocode/kubeconfig"]
        volumeMounts:
        - name: cluster-details-wolke7-nocode
          mountPath: "/tmp/cluster-details-wolke7-nocode"
          readOnly: true
        - name: argocd-initial-admin-secret 
          mountPath: "/tmp/argocd-initial-admin-secret"
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: cluster-details-wolke7-nocode
        secret:
          secretName: cluster-details-wolke7-nocode
      - name: argocd-initial-admin-secret 
        secret:
          secretName: argocd-initial-admin-secret 