apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-civo
  labels:
    provider: civo
    cluster: ck
spec:
  compositeTypeRef:
    apiVersion: wolke7.info/v1alpha1
    kind: CompositeCluster
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: civocluster
    base:
      apiVersion: cluster.civo.crossplane.io/v1alpha1
      kind: CivoKubernetes
      spec:
        instances: 2
        size: g3.k3s.small
        connectionDetails:
          connectionSecretNamePrefix: "cluster-details"
          connectionSecretNamespace: "argocd"
        providerConfigRef:
          name: provider-civo
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.name
    - fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.instanced
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.size
      transforms:
        - type: map
          map:
            small: g3.k3s.small
            medium: g3.k3s.medium
            large: g3.k3s.xlarge
