apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wolke7-infra-crossplane
  namespace: argocd
spec:
  destination:
    name: wolke7-infra
    namespace: crossplane-system
  project: default
  source:
    chart: crossplane
    repoURL: https://github.com/ripro-patrick/wolke7-helm-subcharts.git
