apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wolke7-infra-grafana
  namespace: argocd
spec:
  destination:
    name: wolke7-infra
    namespace: grafana
  project: default
  source:
    path: grafana
    repoURL: https://github.com/ripro-patrick/wolke7-helm-subcharts.git
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
