apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wolke7-infra-rancher
  namespace: argocd
spec:
  destination:
    name: wolke7-infra
  project: default
  source:
    path: rancher
    repoURL: https://github.com/ripro-patrick/wolke7-helm-subcharts.git
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
